//! Opaque identities generated by the canonical run.
//!
//! None of these types accepts a caller string, seed, or world label. The
//! transcript assigns identities from its own append order after the physical
//! event that permits the identity has been recorded.

use std::fmt;

/// Stable identity of one event in an append-only [`RunTranscript`](super::RunTranscript).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct EventId(u64);

impl EventId {
    pub(super) const fn generated(ordinal: u64) -> Self {
        Self(ordinal)
    }

    /// Zero-based position of this event in its transcript.
    pub const fn ordinal(self) -> u64 {
        self.0
    }
}

impl fmt::Display for EventId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "event:{:016}", self.0)
    }
}

/// Identity of one generated contingency draw.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ContingencyDrawId(EventId);

impl ContingencyDrawId {
    pub(super) const fn generated(event: EventId) -> Self {
        Self(event)
    }

    /// Event that generated this draw.
    pub const fn event(self) -> EventId {
        self.0
    }
}

impl fmt::Display for ContingencyDrawId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "contingency:{}", self.0)
    }
}

/// Stable `[W]` identity of one realized physical run.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RealizationId {
    text: String,
    source_draw: ContingencyDrawId,
}

impl RealizationId {
    pub(super) fn generated(source_draw: ContingencyDrawId) -> Self {
        Self {
            text: format!("realization:{}", source_draw.event()),
            source_draw,
        }
    }

    /// Stable readable form assigned by the transcript.
    pub fn as_str(&self) -> &str {
        &self.text
    }

    /// Physical contingency event from which this identity was generated.
    pub const fn source_draw(&self) -> ContingencyDrawId {
        self.source_draw
    }
}

impl fmt::Display for RealizationId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.text)
    }
}

/// Stable identity of one body generated within a realized system.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BodyId {
    text: String,
    birth_event: EventId,
    local_ordinal: u32,
}

impl BodyId {
    #[cfg(test)]
    pub(super) fn generated(birth_event: EventId, local_ordinal: u32) -> Self {
        Self {
            text: format!("body:{birth_event}:{local_ordinal:08}"),
            birth_event,
            local_ordinal,
        }
    }

    /// Stable readable form assigned by the transcript.
    pub fn as_str(&self) -> &str {
        &self.text
    }

    /// Event at which the body entered the physical lineage.
    pub const fn birth_event(&self) -> EventId {
        self.birth_event
    }

    /// Distinguishes multiple bodies born by the same physical event.
    pub const fn local_ordinal(&self) -> u32 {
        self.local_ordinal
    }
}

impl fmt::Display for BodyId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.text)
    }
}

/// Stable identity of a conserved physical reservoir.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ReservoirId {
    text: String,
    creation_event: EventId,
    local_ordinal: u32,
}

impl ReservoirId {
    #[cfg(test)]
    pub(super) fn generated(creation_event: EventId, local_ordinal: u32) -> Self {
        Self {
            text: format!("reservoir:{creation_event}:{local_ordinal:08}"),
            creation_event,
            local_ordinal,
        }
    }

    /// Stable readable form assigned by the transcript.
    pub fn as_str(&self) -> &str {
        &self.text
    }

    /// Event at which the reservoir entered the physical accounting graph.
    pub const fn creation_event(&self) -> EventId {
        self.creation_event
    }

    /// Distinguishes multiple reservoirs created by one event.
    pub const fn local_ordinal(&self) -> u32 {
        self.local_ordinal
    }
}

impl fmt::Display for ReservoirId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.text)
    }
}
