//! Immutable handoff from planet evolution to observation.

use super::{RealizationId, RunReceipt, RunTranscript};

/// A completed planet result that an observer may read but cannot advance.
///
/// This first shell deliberately exposes only identity and the completion
/// receipt. Physical fields join it as their canonical stage ownership lands;
/// until then no public constructor exists and the pipeline cannot emit one.
/// Keeping construction private prevents a viewer or fixture from promoting a
/// partial scene into a canonical snapshot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlanetSnapshot {
    realization_id: RealizationId,
    receipt: RunReceipt,
}

impl PlanetSnapshot {
    #[cfg(test)]
    pub(crate) fn from_complete(receipt: RunReceipt) -> Option<Self> {
        if !receipt.is_complete() {
            return None;
        }
        let realization_id = receipt.realization_id()?.clone();
        Some(Self {
            realization_id,
            receipt,
        })
    }

    /// Stable `[W]` identity generated by the realized world.
    pub fn realization_id(&self) -> &str {
        self.realization_id.as_str()
    }

    /// Opaque generated identity, including its source contingency event.
    pub const fn realization_identity(&self) -> &RealizationId {
        &self.realization_id
    }

    /// Completion and provenance receipt associated with this immutable state.
    pub fn receipt(&self) -> &RunReceipt {
        &self.receipt
    }

    /// Complete immutable causal transcript carried by the snapshot.
    pub const fn transcript(&self) -> &RunTranscript {
        self.receipt.transcript()
    }
}

#[cfg(test)]
mod tests {
    use crate::canonical::{readiness_receipt, PlanetRunOutcome, PlanetSnapshot};

    #[test]
    fn a_refusal_cannot_be_promoted_to_a_snapshot() {
        let outcome = PlanetRunOutcome::Refused(readiness_receipt());
        assert!(outcome.snapshot().is_none());
        assert!(PlanetSnapshot::from_complete(outcome.receipt().clone()).is_none());
    }
}
