#!/usr/bin/env python3
# Copyright 2026 Nathan M. Fraske
# Licensed under the Apache License, Version 2.0; see LICENSE.
#
# Generates docs/working/PHYSICS_FLOOR_REGISTRY.md: the derive-first audit map of the physics substrate.
# Presence here is discovery, not admission. The canonical run accepts only the repository-owned
# absolute-floor catalog; a reference row, citation, axis, or provenance tag in this report cannot
# authorize a value. The report is also the "where do I look for this law" index, so it lists every
# declared floor law and direct laws.rs kernel with its file:line.
#
# The floor TOMLs carry three block kinds, and the registry keeps them distinct because they are
# not the same audit category:
#   [[axis]]      quantity schemas and stored reference columns still requiring derive-first review.
#   [[substance]] reference materials (iron, oak), vectors over those axes; never world inputs merely
#                 because they are present or cited.
#   [[law]]       declared law kernels: fixed Rust, not value-bearing input.
# A fourth source is scanned so nothing hides from the map:
#   crates/physics/src/laws.rs   the DIRECT law kernels (every `pub fn`), some backed by a declared
#                 [[law]] block, some called directly by consumers (the spreading law, the transduction
#                 family). A direct kernel adds no authored value (it reads existing axes/constants),
#                 but it IS a floor law mechanism, so it belongs on the map for findability.
#
# Generated with each entry's file:line, so the list never drifts; the floor-registry stop-gate
# regenerates this file to a temp and blocks if the committed one is stale. Deterministic output
# (file order, no timestamps) so regenerate-and-diff is clean equality.

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# A positional output path, ignoring FLAGS. Taking `sys.argv[1]` unconditionally made `--check` read as
# an output filename, so the check reported the registry "MISSING at --check" while the real one sat
# untouched beside it. A flag that silently becomes a path is a check that silently tests nothing.
_POSITIONAL = [a for a in sys.argv[1:] if not a.startswith("-")]
OUT = (
    os.path.abspath(_POSITIONAL[0])
    if _POSITIONAL
    else os.path.join(ROOT, "docs/working/PHYSICS_FLOOR_REGISTRY.md")
)
LAWS_RS_REL = "crates/physics/src/laws.rs"


def repo_rel(path):
    """Return a stable repository path on every host."""
    return os.path.relpath(path, ROOT).replace(os.sep, "/")

# Physical-floor invariants, noncausal representation roots, and derived SI
# relations reached by the current substrate. This is an audit index, while the
# authoritative admitted membership and counts are generated by ledger_inventory.
UNIVERSAL = [
    ("[M] admitted physical invariants (alpha, G, m_e)", "CODATA plus derive-first exhaustion receipts", "the sealed repository-owned absolute floor in crates/planet"),
    ("SI representation definitions (no provenance tag)", "Delta_nu_Cs, c, h, e, k_B, N_A, K_cd", "versioned noncausal schema in crates/units; exact SI values encode all seven base coordinates but do not authorize physics"),
    ("[D] vacuum permittivity eps_0", "e^2/(2*alpha*h*c)", "computed by crates/units from one admitted physical invariant plus the SI schema"),
    ("representation-derived Stefan-Boltzmann sigma", "2*pi^5*k_B^4/(15*h^3*c^2)", "computed by crates/units; no independent physical leaf"),
    ("representation-derived gas constant R", "N_A*k_B", "computed by crates/units; no independent physical leaf"),
    ("representation-derived atomic-volume conversion", "10^24/N_A angstrom^3/(cm^3/mol)", "computed by crates/units; no independent physical leaf"),
    ("[D, migration owed] Coulomb constant k", "1/(4*pi*eps_0)", "the electromagnetic registry must consume the derived relation, not an independent decimal"),
    ("[D, migration owed] vacuum permeability mu_0", "1/(eps_0*c^2)", "the electromagnetic registry must consume the derived relation, not an independent decimal"),
]


def parse_floor(path):
    """Return (axes, substances, laws). axes/substances are (id, line, unit, measures); laws are
    (id, line, kernel). Each id is classified by the most recent [[kind]] header above it."""
    with open(path, encoding="utf-8") as fh:
        lines = fh.readlines()
    axes, substances, laws = [], [], []
    kind = None
    for i, ln in enumerate(lines):
        h = re.match(r"^\[\[([a-z_]+)\]\]", ln)
        if h:
            kind = h.group(1)
            continue
        m = re.match(r'^id = "([^"]+)"', ln)
        if not m:
            continue
        aid = m.group(1)
        unit = ""
        measures = ""
        kernel = ""
        for j in range(i, min(i + 8, len(lines))):
            mu = re.match(r'^unit = "(.*)"\s*$', lines[j])
            if mu and not unit:
                unit = mu.group(1)
            mm = re.match(r'^measures = "(.*)"\s*$', lines[j])
            if mm and not measures:
                measures = mm.group(1)
            mk = re.match(r'^kernel = "(.*)"\s*$', lines[j])
            if mk and not kernel:
                kernel = mk.group(1)
        if kind == "axis":
            axes.append((aid, i + 1, unit, measures))
        elif kind == "substance":
            substances.append((aid, i + 1, unit, measures))
        elif kind == "law":
            laws.append((aid, i + 1, kernel))
    return axes, substances, laws


def parse_laws_rs(path):
    """Return [(name, line, summary)] for every `pub fn` in laws.rs, in file order (deterministic).
    summary is the first DESCRIPTIVE line of the doc comment immediately above the fn, if any.

    DESCRIPTIVE, not merely FIRST, and the difference is a defect this file already suffered. Two consumers
    independently claimed the position "first doc line": this reader took it as the excerpt, and the diamond
    gate's `@provides` annotation was written there. The collision made the enforced derive-vs-author reference
    stop describing two kernels and recite their annotations back ("@provides thermal_boundary_layer" as the
    summary of `thermal_boundary_layer`). That is the POSITIONAL-CONVENTION COLLISION class: two conventions
    agreeing on a slot and disagreeing about its meaning, which the stop gate caught and no other check could.

    The repair is SEMANTIC rather than positional (owner ruling): annotation lines are SKIPPED rather than
    reserved a position, so "the excerpt is the first descriptive line" holds no matter where an annotation is
    placed, and the NEXT annotation convention cannot re-break it. Placing `@provides` last is the current
    convention and is now a convenience rather than a load-bearing requirement.
    """
    with open(path, encoding="utf-8") as fh:
        lines = fh.readlines()
    kernels = []
    summary = None
    for i, ln in enumerate(lines):
        s = ln.strip()
        mdoc = re.match(r"^///\s?(.*)", s)
        if mdoc:
            text = mdoc.group(1).strip()
            # An annotation is machinery for another reader, never a description of the kernel. Skipping it
            # keeps this excerpt semantic; reserving it a position would only move the collision.
            if summary is None and text and not text.startswith("@"):
                summary = text
            continue
        mfn = re.match(r"^pub fn ([a-z0-9_]+)", ln)
        if mfn:
            kernels.append((mfn.group(1), i + 1, summary or ""))
            summary = None
            continue
        if s == "" or s.startswith("#["):
            # blank lines and attributes sit between a doc block and its fn; keep the pending summary.
            continue
        summary = None  # any other line ends the pending doc block
    return kernels


def scan_derives(root):
    """Scan every .rs under crates/ for `// @derives:` markers, the deriving-substrate index.

    A marker sits at a derivation entry point (a subsystem that produces a world quantity from the
    floor and the situation) and reads `// @derives[<id>]: <quantity> <- <from these substrate
    inputs>`, or the bare `// @derives:` form. The optional `[<id>]` token is the machine handle the
    derived-output-is-live gate keys its `Derivation` registry to (tasks #43, #46); it is
    ignored here, so both forms land on the billboard.
    The generator emits every marker with its file:line, so the deriving half of the substrate map
    (orbital mechanics, hydrology, metabolism, the matter cycle, the time-space anchors: everything
    OUTSIDE crates/physics) is on the billboard and the stop-gate keeps it never-stale, exactly as
    it does the authored floor. Returns [(rel, line, text)] sorted by (file, line) for deterministic
    output. This is the derive-FROM list: an agent about to author a value checks here first, and a
    quantity found here is a defect to author because a substrate already derives it."""
    out = []
    for path in sorted(glob.glob(os.path.join(root, "crates/**/*.rs"), recursive=True)):
        rel = os.path.relpath(path, root).replace(os.sep, "/")
        with open(path, encoding="utf-8") as fh:
            for i, ln in enumerate(fh):
                m = re.search(r"//\s*@derives(?:\[\w+\])?:\s*(.*\S)", ln)
                if m:
                    out.append((rel, i + 1, m.group(1).strip()))
    out.sort(key=lambda t: (t[0], t[1]))
    return out


def render_entries(body, rel, entries):
    for aid, line, unit, measures in entries:
        u = f" [{unit}]" if unit else ""
        meas = (measures[:150] + "...") if len(measures) > 150 else measures
        tail = f": {meas}" if meas else ""
        body.append(f"- `{aid}`{u} ({rel}:{line}){tail}")


def main():
    # floor_provenance.toml is the candidate-evidence audit sidecar, keyed by broad-data entry id. It is not
    # canonical admission and is not a physics manifest of axes, laws, or substances, so exclude it here.
    floors = sorted(
        f
        for f in glob.glob(os.path.join(ROOT, "crates/physics/data/*.toml"))
        if os.path.basename(f) != "floor_provenance.toml"
    )
    parsed = [(repo_rel(f), *parse_floor(f)) for f in floors]
    n_axes = sum(len(a) for _, a, _, _ in parsed)
    n_sub = sum(len(s) for _, _, s, _ in parsed)
    n_law = sum(len(lw) for _, _, _, lw in parsed)
    laws_rs = parse_laws_rs(os.path.join(ROOT, LAWS_RS_REL))
    declared_kernels = {k for _, _, _, lw in parsed for _, _, k in lw if k}
    n_kernels = len(laws_rs)
    n_direct = sum(1 for name, _, _ in laws_rs if name not in declared_kernels)
    derives = scan_derives(ROOT)
    n_derives = len(derives)

    body = []
    body.append("# Physics substrate audit registry (what exists, and what must derive)")
    body.append("")
    body.append(
        "This is a derive-first audit and discovery map, not an admission list. The authoritative canonical "
        "membership is `docs/working/CANONICAL_LEDGER_INVENTORY.txt`, generated from the repository-owned "
        "absolute-floor catalog. A citation, provenance tag, stored axis, substance row, or appearance in "
        "this report never authorizes a value at the planet front door. This report inventories candidate "
        "reference columns and every floor LAW with its file:line so it doubles as the \"where do I look for "
        "this law\" index. "
        "The DERIVING-SUBSTRATE half (the section right below the constants) is every subsystem OUTSIDE the "
        "physics crate that derives a world quantity from the floor and the situation: orbital mechanics, "
        "the hydrology cycle, productivity, metabolism, the matter cycle, the time-space anchors. The "
        "derive-vs-author rule it makes concrete: a value must first DERIVE from the absolute floor and "
        "situation, and the deriving-substrate "
        "list is where you look for the substrate that derives it BEFORE you ever author a number. If a "
        "quantity you were about to author appears in the deriving-substrate list, authoring it is a "
        "defect. Only an irreducible remainder that survives the derivation hunter, Buckingham-Pi budget, "
        "Gap Law, and Residual Law may extend the floor. Written state and contingency are generated inside "
        "the run from admitted physical measures and the approved realization-coordinate law, never "
        "supplied as world values or caller seeds."
    )
    body.append("")
    body.append(
        f"There are {n_axes} stored material and quantity AXES across {len(floors)} candidate-reference "
        f"files. The same files carry {n_sub} reference SUBSTANCES as vectors over those axes. These are "
        "migration and derivation-hunt populations, not automatically admitted floor values. The "
        f"floor laws are {n_law} DECLARED laws (the `[[law]]` blocks in the floor data) plus {n_kernels} "
        f"direct kernels in `{LAWS_RS_REL}` ({n_direct} of them not backed by a declared block, called "
        "called directly), all listed below. A law kernel is fixed Rust, not a value-bearing input; every "
        "magnitude it consumes still owes the absolute-floor admission contract."
    )
    body.append("")
    body.append(
        "The lists below are GENERATED from `crates/physics/data/*.toml`, `" + LAWS_RS_REL + "`, and every "
        "`// @derives:` marker across `crates/**/*.rs` by `scripts/gen_floor_registry.py`, with each "
        "entry's `file:line`, so they never drift. Do NOT edit this file by hand: change the floor data, "
        "add the law kernel, or place the `// @derives:` marker at the deriving subsystem, then run the "
        "generator (the floor-registry stop-gate regenerates and blocks if this file is stale). To ADD a "
        "floor axis, a law kernel, or a deriving substrate is a deliberate act; the diff to this registry "
        "is the record of it. When you build a new subsystem that derives a world quantity, mark it with "
        "`// @derives: <quantity> <- <from these inputs>` so it lands on this billboard and no future "
        "agent authors from the ether what your subsystem already derives."
    )
    body.append("")
    body.append("## Physical invariants, representation schema, and derived relations (audit index)")
    body.append("")
    for name, value, where in UNIVERSAL:
        body.append(f"- **{name}** = {value} ({where})")
    body.append("")
    body.append("## Deriving substrates (check here BEFORE authoring: what the world derives, and where)")
    body.append("")
    body.append(
        f"The {n_derives} deriving subsystems below live outside the absolute floor. Each produces a "
        "world quantity from the floor and the situation, so its output must never be authored: if the "
        "value you need appears here, read or extend the subsystem, do not set a number. This is the "
        "list that stops `1 year = 365 days` from being authored when orbital mechanics already derives "
        "it. Generated from the `// @derives:` markers in the code; a subsystem missing its marker is a "
        "gap in this map, so mark every derivation entry point."
    )
    body.append("")
    if derives:
        cur = None
        for rel, line, text in derives:
            if rel != cur:
                body.append(f"### `{rel}`")
                body.append("")
                cur = rel
            body.append(f"- {text} (`{rel}:{line}`)")
        body.append("")
    else:
        body.append("_No `// @derives:` markers found yet. Place them at each deriving subsystem._")
        body.append("")
    body.append("## Stored material and quantity axes (derive-first audit population)")
    body.append("")
    for rel, axes, _, _ in parsed:
        if not axes:
            continue
        body.append(f"### `{rel}` ({len(axes)} axes)")
        body.append("")
        render_entries(body, rel, axes)
        body.append("")
    body.append("## Reference substances (candidate rows, not runpath admission)")
    body.append("")
    for rel, _, subs, _ in parsed:
        if not subs:
            continue
        body.append(f"### `{rel}` ({len(subs)} substances)")
        body.append("")
        render_entries(body, rel, subs)
        body.append("")
    body.append("## Law kernels (fixed Rust mechanisms, not authored values)")
    body.append("")
    body.append(
        "Two kinds, kept distinct: a DECLARED law is a `[[law]]` block in the floor data (it names the "
        "kernel it runs); a DIRECT kernel is a `pub fn` in `" + LAWS_RS_REL + "`. Every direct kernel is "
        "listed, tagged `[direct]` when no declared block backs it (a consumer calls it directly, for "
        "example the general spreading law and the transduction family). This section is the law index: "
        "to find where a law lives, look here."
    )
    body.append("")
    body.append("### Declared laws (`[[law]]` blocks in the floor data)")
    body.append("")
    for rel, _, _, laws in parsed:
        if not laws:
            continue
        body.append(f"#### `{rel}` ({len(laws)} laws)")
        body.append("")
        for lid, line, kernel in laws:
            k = f" -> `{kernel}`" if kernel else ""
            body.append(f"- `{lid}`{k} ({rel}:{line})")
        body.append("")
    body.append(f"### Direct kernels (`{LAWS_RS_REL}`, {n_kernels} `pub fn`, {n_direct} unbacked)")
    body.append("")
    for name, line, summary in laws_rs:
        tag = "" if name in declared_kernels else " [direct]"
        s = (summary[:150] + "...") if len(summary) > 150 else summary
        tail = f": {s}" if s else ""
        body.append(f"- `{name}`{tag} ({LAWS_RS_REL}:{line}){tail}")
    body.append("")
    rendered = "\n".join(body).rstrip() + "\n"
    summary = (
        f"{n_axes} axes, {n_sub} substances, {n_law} declared laws, "
        f"{n_kernels} laws.rs kernels ({n_direct} direct), {n_derives} deriving substrates"
    )

    # `--check` EXISTS BECAUSE THE ADVERTISED STOP GATE DID NOT. The registry's own header says a stop
    # gate regenerates it and blocks stale output, and no CI job and no Stone 0 path ran this script: the
    # only thing enforcing it was a LOCAL Claude Code hook, invisible to CI, to main, and to anyone else.
    # A generator that always writes cannot convict staleness, so hand-editing the registry, adding a floor
    # law, or changing a `@derives` marker went unnoticed anywhere but one machine.
    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            print(f"floor registry MISSING at {repo_rel(OUT)}; run this script.")
            return 1
        with open(OUT, encoding="utf-8") as fh:
            current = fh.read()
        if current != rendered:
            print(
                f"floor registry STALE at {repo_rel(OUT)}. The generated content no longer "
                f"matches the tree ({summary}). Run `python3 scripts/gen_floor_registry.py` and commit "
                f"the result. This is the enforced derive-versus-author reference: a stale one is a WRONG "
                f"reference, so it fails rather than warns."
            )
            return 1
        print(f"floor registry current: {summary}")
        return 0

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"wrote {repo_rel(OUT)}: {summary}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
