#!/usr/bin/env python3
# Copyright 2026 Nathan M. Fraske
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate the MIRRORED half of the source registry, and the centralized bibliography.

THE CONSOLIDATION THIS IMPLEMENTS (docs/working/FETCH_PIPELINE_PLAN.md). Vendored sources live in five
places: 27 `[[source]]` blocks across 18 per-directory manifests, one prose entry in
docs/working/VENDORING_CHECKLIST.md, 31 entries on PR #201's disk_arc_literature manifest, the prose
bibliography in docs/design.md Part 63, and 28 MB of bytes outside the repo in ~/.claude/vendored-sources/.
A reader asking "what do we hold, and is it checksummed and archived?" had five places to look and no
single answer.

THE TWO-FILE SPLIT, AND WHY IT IS NOT A DIAMOND. `sources/registry.toml` is hand-maintained and is where a
NEW fetch lands. `sources/mirrored.toml` is GENERATED by this script from the per-directory manifests and
is never hand-edited. Both are read as ONE namespace by the gate and by the bibliography, so there is one
lookup and one bibliography.

The repo's own diamond gate states the predicate: two providers are not a defect, an UNARBITRATED two
providers is. The arbitration here is registered and one-directional. For a mirrored entry the MANIFEST is
the authority: the entry carries `mirrors = "<manifest path>"`, this script copies the fields down, and
scripts/sources_gate.py fails if the generated file is stale against its manifests. A mirrored entry can
therefore never disagree with its manifest, because it is not a second copy anybody edits. For a registry
entry there is no manifest and the registry is the authority. Every id lives in exactly one of the two.

The per-directory manifests keep their `[[source]]` blocks because they sit beside the bytes they index
and because `*_provenance_test.py` reads them. Moving them would break loaders and collide with concurrent
work for no gain the mirror does not already deliver.

Usage:
  scripts/gen_sources.py               regenerate sources/mirrored.toml and docs/SOURCES.md
  scripts/gen_sources.py --check       exit 1 if either is stale (what the gate calls)
  scripts/gen_sources.py --self-test   parser and id-derivation check on synthetic input
"""

import hashlib
import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
MIRRORED = ROOT / "sources" / "mirrored.toml"
REGISTRY = ROOT / "sources" / "registry.toml"
LICENCES = ROOT / "sources" / "licences.toml"
BIBLIOGRAPHY = ROOT / "docs" / "SOURCES.md"

# The manifests to mirror. disk_arc_literature is DELIBERATELY EXCLUDED while PR #201 is in flight: it is
# read-only to this lane by instruction, and mirroring a file another agent is actively appending to would
# make this generator's output flap. It joins the mirror in one line when that PR lands.
MANIFEST_GLOB = "crates/*/data/*/manifest.toml"
EXCLUDED_DIRS = {"disk_arc_literature"}

# Fields copied down from a manifest `[[source]]` block, in emit order. `archive_url` is PR #201's spelling
# of `archived_url`; both are accepted everywhere so neither lane has to rename on a live branch.
MIRRORED_FIELDS = [
    "citation",
    "url",
    "archived_url",
    "archive_url",
    "archive_pending",
    "sha256",
    "md5",
    "bytes",
    "pages",
    "recipe",
    "grade",
    "scope",
    "anchor",
    "extract",
    "used_by",
    "note",
]


def derive_id(dirname, block, n_in_file):
    """The stable registry id for a manifest source block.

    A directory holding ONE source is keyed by the directory (`byerlee_1978`), which reads naturally and is
    what a citation would say. A directory holding SEVERAL is keyed `<dir>.<name>` so the ids stay unique
    and still sort together. A block with no `name` in a multi-source file falls back to its index, which
    is a defect the gate reports rather than a silent collision.
    """
    name = block.get("name")
    if n_in_file == 1:
        return dirname
    if name:
        return f"{dirname}.{name}"
    return None


def collect(read_toml, manifest_paths):
    """[(id, dirname, rel_manifest_path, block)] sorted by id, plus the list of id-derivation problems."""
    out = []
    problems = []
    for path in manifest_paths:
        dirname = path.parent.name
        if dirname in EXCLUDED_DIRS:
            continue
        try:
            data = read_toml(path)
        except Exception as exc:  # a malformed manifest is a reportable defect, not a crash
            problems.append(f"{path}: does not parse ({exc})")
            continue
        blocks = data.get("source", [])
        rel = str(path.relative_to(ROOT))
        for block in blocks:
            sid = derive_id(dirname, block, len(blocks))
            if sid is None:
                problems.append(
                    f"{rel}: a source block in a multi-source manifest has no `name`, so it has no stable id"
                )
                continue
            out.append((sid, dirname, rel, block))
    out.sort(key=lambda t: t[0])
    seen = {}
    for sid, _, rel, _ in out:
        if sid in seen:
            problems.append(f"duplicate source id '{sid}' from {seen[sid]} and {rel}")
        seen[sid] = rel
    return out, problems


def render_mirrored(collected):
    """The generated mirror. Deterministic: entries sorted by id, fields in a fixed order."""
    lines = [
        "# GENERATED by scripts/gen_sources.py. Do not edit by hand.",
        "#",
        "# The MIRRORED half of the source registry: every `[[source]]` block in the per-directory",
        "# manifests, copied down under a stable id so the whole vendored population has ONE lookup.",
        "# The manifest named in `mirrors` is the AUTHORITY for each entry; this file is a generated view",
        "# of it, so the two cannot disagree (scripts/sources_gate.py fails if this file is stale).",
        "#",
        "# A NEW fetch does not land here. It lands in sources/registry.toml, which is hand-maintained.",
        "# The gate and the bibliography read both files as one namespace.",
        "#",
        f"# Entries: {len(collected)}",
        "",
    ]
    for sid, _dirname, rel, block in collected:
        lines.append("[[source]]")
        lines.append(f'id = "{sid}"')
        lines.append(f'mirrors = "{rel}"')
        if "file" in block:
            holding = str(pathlib.Path(rel).parent / block["file"])
            # A `dir` field means the bytes live under a sibling directory (the gruneisen cross-reference
            # idiom), so the holding path is resolved there rather than beside this manifest.
            if "dir" in block:
                holding = str(
                    pathlib.Path(rel).parent.parent / block["dir"] / block["file"]
                )
            lines.append(f'holding = "{holding}"')
        for field in MIRRORED_FIELDS:
            if field not in block:
                continue
            val = block[field]
            if isinstance(val, bool):
                lines.append(f"{field} = {str(val).lower()}")
            elif isinstance(val, int):
                lines.append(f"{field} = {val}")
            else:
                escaped = str(val).replace("\\", "\\\\").replace('"', '\\"')
                lines.append(f'{field} = "{escaped}"')
        lines.append("")
    return "\n".join(lines)


def load_registry(read_toml):
    """The hand-maintained half. Absent is legal: the mirror alone is a working registry."""
    if not REGISTRY.exists():
        return []
    try:
        return read_toml(REGISTRY).get("source", [])
    except Exception:
        return []


def load_licences(read_toml):
    """The licence overlay, id -> finding. The bibliography is what a reader trusts, so the redistribution
    status has to appear there rather than only inside the gate."""
    if not LICENCES.exists():
        return {}
    try:
        return {r["id"]: r for r in read_toml(LICENCES).get("licence", []) if r.get("id")}
    except Exception:
        return {}


def render_bibliography(collected, registry_entries, licences=None):
    """docs/SOURCES.md: the centralized bibliography, generated so it cannot drift from the held bytes."""
    licences = licences or {}
    total = len(collected) + len(registry_entries)
    lines = [
        "# Sources: the centralized bibliography",
        "",
        "GENERATED by `scripts/gen_sources.py`. Do not edit by hand.",
        "",
        "Every source the project holds or witnesses, with its citation, its checksum, where the bytes are,",
        "and whether an archive snapshot stands behind the link. This is the single bibliography for the",
        "vendored population: `sources/registry.toml` (hand-maintained, where a new fetch lands) and",
        "`sources/mirrored.toml` (generated from the per-directory manifests) read as one namespace.",
        "",
        "Custody is one of three. `in_repo`: bytes held in-tree, checksum verifiable with no network.",
        "`witness`: bytes not held, the checksum is a re-fetch receipt and the archive URL is the public",
        "witness. `external`: bytes in local custody outside the repo, checksum plus archive snapshot.",
        "The licence decides which is permitted; see `docs/working/FETCH_PIPELINE_PLAN.md` section 3.",
        "",
        f"**{total} sources** ({len(registry_entries)} registry, {len(collected)} mirrored).",
        "",
    ]

    def emit(sid, block, mirrors=None):
        # The overlay finding wins over anything inline, because it is the reviewed one.
        block = {**block, **{k: v for k, v in licences.get(sid, {}).items() if k != "id"}}
        cite = block.get("citation", "(no citation recorded)")
        lines.append(f"### `{sid}`")
        lines.append("")
        lines.append(cite)
        lines.append("")
        sha = block.get("sha256")
        if sha:
            lines.append(f"- sha256: `{sha}`")
        elif block.get("md5"):
            lines.append(f"- md5 (legacy receipt, no sha256): `{block['md5']}`")
        else:
            lines.append("- checksum: NONE RECORDED")
        arch = block.get("archived_url") or block.get("archive_url")
        if arch:
            lines.append(f"- archived: {arch}")
        elif block.get("archive_pending"):
            lines.append(f"- archive pending: {block['archive_pending']}")
        else:
            lines.append("- archived: NONE RECORDED")
        if block.get("scope"):
            lines.append(f"- scope: {block['scope']}")
        if block.get("custody"):
            lines.append(f"- custody: {block['custody']}")
        if block.get("licence"):
            redist = block.get("redistributable")
            if redist is True:
                tag = "redistributable"
            elif redist is False:
                tag = "**NOT redistributable**"
            else:
                tag = "redistribution unconfirmed"
            lines.append(f"- licence ({tag}): {block['licence']}")
            if block.get("licence_evidence"):
                lines.append(f"- licence evidence: {block['licence_evidence']}")
            if block.get("remediation"):
                lines.append(f"- remediation: {block['remediation']}")
        if block.get("free_route"):
            lines.append(f"- free route ({block.get('free_route_kind','unspecified')}): {block['free_route']}")
        if block.get("holding"):
            lines.append(f"- holding: `{block['holding']}`")
        if mirrors:
            lines.append(f"- authority: `{mirrors}`")
        lines.append("")

    if registry_entries:
        lines.append("## Registry (hand-maintained)")
        lines.append("")
        for block in sorted(registry_entries, key=lambda b: b.get("id", "")):
            emit(block.get("id", "(no id)"), block)

    lines.append("## Mirrored from the per-directory manifests")
    lines.append("")
    for sid, _dirname, rel, block in collected:
        emit(sid, block, mirrors=rel)

    return "\n".join(lines) + "\n"


def _read_toml(path):
    with open(path, "rb") as fh:
        return tomllib.load(fh)


def _digest(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def build(read_toml=_read_toml):
    paths = sorted(ROOT.glob(MANIFEST_GLOB))
    collected, problems = collect(read_toml, paths)
    registry_entries = load_registry(read_toml)
    licences = load_licences(read_toml)
    return collected, problems, render_mirrored(collected), render_bibliography(
        collected, registry_entries, licences
    )


def self_test():
    """Exercise id derivation and the mirror render on synthetic input, no filesystem."""
    single = {"source": [{"citation": "C", "sha256": "a" * 64, "file": "x.pdf"}]}
    multi = {
        "source": [
            {"name": "one", "citation": "C1", "sha256": "b" * 64},
            {"name": "two", "citation": "C2", "sha256": "c" * 64},
        ]
    }
    nameless_multi = {"source": [{"citation": "C1"}, {"citation": "C2"}]}

    fake = {
        ROOT / "crates/x/data/solo/manifest.toml": single,
        ROOT / "crates/x/data/pair/manifest.toml": multi,
        ROOT / "crates/x/data/bad/manifest.toml": nameless_multi,
    }

    def reader(path):
        return fake[path]

    collected, problems = collect(reader, list(fake))
    ids = [c[0] for c in collected]
    assert ids == ["pair.one", "pair.two", "solo"], f"id derivation: {ids}"
    assert len(problems) == 2, f"two nameless multi-source blocks must be reported, got {problems}"

    # The holding path is resolved beside the manifest.
    text = render_mirrored(collected)
    assert 'holding = "crates/x/data/solo/x.pdf"' in text, "holding path must resolve beside the manifest"
    assert 'mirrors = "crates/x/data/solo/manifest.toml"' in text, "the authority must be named"
    # Deterministic: the same input renders identically.
    assert text == render_mirrored(collected), "render must be deterministic"
    # A quote in a citation must not break the TOML it is emitted into.
    quoted, _ = collect(
        lambda p: {"source": [{"citation": 'He said "hi"', "sha256": "d" * 64}]},
        [ROOT / "crates/x/data/q/manifest.toml"],
    )
    out = render_mirrored(quoted)
    assert '\\"hi\\"' in out, "a quote in a citation must be escaped"
    tomllib.loads(out)  # the escaped render must be valid TOML
    print("gen_sources self-test: OK")
    return 0


def main():
    args = sys.argv[1:]
    if "--self-test" in args:
        return self_test()

    collected, problems, mirrored_text, biblio_text = build()

    if problems:
        print("gen_sources: manifest problems:", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)

    if "--check" in args:
        stale = []
        if not MIRRORED.exists() or _digest(MIRRORED.read_text(encoding="utf-8")) != _digest(
            mirrored_text
        ):
            stale.append(str(MIRRORED.relative_to(ROOT)))
        if not BIBLIOGRAPHY.exists() or _digest(
            BIBLIOGRAPHY.read_text(encoding="utf-8")
        ) != _digest(biblio_text):
            stale.append(str(BIBLIOGRAPHY.relative_to(ROOT)))
        if stale:
            print(
                "gen_sources: STALE generated file(s): " + ", ".join(stale) + "\n"
                "Run: python3 scripts/gen_sources.py   then commit them. A stale mirror is a wrong "
                "registry, and the bibliography is the thing readers trust.",
                file=sys.stderr,
            )
            return 1
        print(f"gen_sources: generated files current ({len(collected)} mirrored sources)")
        return 0

    MIRRORED.parent.mkdir(parents=True, exist_ok=True)
    MIRRORED.write_text(mirrored_text, encoding="utf-8")
    BIBLIOGRAPHY.write_text(biblio_text, encoding="utf-8")
    print(
        f"gen_sources: wrote {MIRRORED.relative_to(ROOT)} ({len(collected)} sources) "
        f"and {BIBLIOGRAPHY.relative_to(ROOT)}"
    )
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
